import { v4 as uuidv4 } from 'uuid';

const blogs =[
    {
      "id":uuidv4(),
      "category":"Business",
      "category2":"Travel",
      "date":"July 2, 2020",
      "title":"Your most unhappy customers are your greatest source of learning.",
      "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
      "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
      "author":"Sergy Campbell",
      "designation":"CEO and Founder",
      "image":"images/person_1.jpg",
      "blog_image":"images/img_2.jpg"
    },
    {
        "id":uuidv4(),
        "category":"Business",
        "category2":"Travel",
        "date":"July 2, 2020",
        "title":"Your most unhappy customers are your greatest source of learning.",
        "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "author":"Sergy Campbell",
        "designation":"CEO and Founder",
        "image":"images/person_1.jpg",
        "blog_image":"images/img_2.jpg"
      },
      {
        "id":uuidv4(),
        "category":"Business",
        "category2":"Travel",
        "date":"July 2, 2020",
        "title":"Your most unhappy customers are your greatest source of learning.",
        "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "author":"Sergy Campbell",
        "designation":"CEO and Founder",
        "image":"images/person_1.jpg",
        "blog_image":"images/img_2.jpg"
      },
      {
        "id":uuidv4(),
        "category":"Business",
        "category2":"Travel",
        "date":"July 2, 2020",
        "title":"Your most unhappy customers are your greatest source of learning.",
        "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "author":"Sergy Campbell",
        "designation":"CEO and Founder",
        "image":"images/person_1.jpg",
        "blog_image":"images/img_2.jpg"
      },
      {
        "id":uuidv4(),
        "category":"Business",
        "category2":"Travel",
        "date":"July 2, 2020",
        "title":"Your most unhappy customers are your greatest source of learning.",
        "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "author":"Sergy Campbell",
        "designation":"CEO and Founder",
        "image":"images/person_1.jpg",
        "blog_image":"images/img_2.jpg"
      },
      {
        "id":uuidv4(),
        "category":"Business",
        "category2":"Travel",
        "date":"July 2, 2020",
        "title":"Your most unhappy customers are your greatest source of learning.",
        "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "author":"Sergy Campbell",
        "designation":"CEO and Founder",
        "image":"images/person_1.jpg",
        "blog_image":"images/img_2.jpg"
      },
      {
        "id":uuidv4(),
        "category":"Business",
        "category2":"Travel",
        "date":"July 2, 2020",
        "title":"Your most unhappy customers are your greatest source of learning.",
        "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
        "author":"Sergy Campbell",
        "designation":"CEO and Founder",
        "image":"images/person_1.jpg",
        "blog_image":"images/img_2.jpg"
      },
      {
          "id":uuidv4(),
          "category":"Business",
          "category2":"Travel",
          "date":"July 2, 2020",
          "title":"Your most unhappy customers are your greatest source of learning.",
          "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "author":"Sergy Campbell",
          "designation":"CEO and Founder",
          "image":"images/person_1.jpg",
          "blog_image":"images/img_2.jpg"
        },
        {
          "id":uuidv4(),
          "category":"Business",
          "category2":"Travel",
          "date":"July 2, 2020",
          "title":"Your most unhappy customers are your greatest source of learning.",
          "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "author":"Sergy Campbell",
          "designation":"CEO and Founder",
          "image":"images/person_1.jpg",
          "blog_image":"images/img_2.jpg"
        },
        {
          "id":uuidv4(),
          "category":"Business",
          "category2":"Travel",
          "date":"July 2, 2020",
          "title":"Your most unhappy customers are your greatest source of learning.",
          "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "author":"Sergy Campbell",
          "designation":"CEO and Founder",
          "image":"images/person_1.jpg",
          "blog_image":"images/img_2.jpg"
        },
        {
          "id":uuidv4(),
          "category":"Business",
          "category2":"Travel",
          "date":"July 2, 2020",
          "title":"Your most unhappy customers are your greatest source of learning.",
          "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "author":"Sergy Campbell",
          "designation":"CEO and Founder",
          "image":"images/person_1.jpg",
          "blog_image":"images/img_2.jpg"
        },
        {
          "id":uuidv4(),
          "category":"Business",
          "category2":"Travel",
          "date":"July 2, 2020",
          "title":"Your most unhappy customers are your greatest source of learning.",
          "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "author":"Sergy Campbell",
          "designation":"CEO and Founder",
          "image":"images/person_1.jpg",
          "blog_image":"images/img_2.jpg"
        } ,
        {
          "id":uuidv4(),
          "category":"Business",
          "category2":"Travel",
          "date":"July 2, 2020",
          "title":"Your most unhappy customers are your greatest source of learning.",
          "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
          "author":"Sergy Campbell",
          "designation":"CEO and Founder",
          "image":"images/person_1.jpg",
          "blog_image":"images/img_2.jpg"
        },
        {
            "id":uuidv4(),
            "category":"Business",
            "category2":"Travel",
            "date":"July 2, 2020",
            "title":"Your most unhappy customers are your greatest source of learning.",
            "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "author":"Sergy Campbell",
            "designation":"CEO and Founder",
            "image":"images/person_1.jpg",
            "blog_image":"images/img_2.jpg"
          },
          {
            "id":uuidv4(),
            "category":"Business",
            "category2":"Travel",
            "date":"July 2, 2020",
            "title":"Your most unhappy customers are your greatest source of learning.",
            "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "author":"Sergy Campbell",
            "designation":"CEO and Founder",
            "image":"images/person_1.jpg",
            "blog_image":"images/img_2.jpg"
          },
          {
            "id":uuidv4(),
            "category":"Business",
            "category2":"Travel",
            "date":"July 2, 2020",
            "title":"Your most unhappy customers are your greatest source of learning.",
            "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "author":"Sergy Campbell",
            "designation":"CEO and Founder",
            "image":"images/person_1.jpg",
            "blog_image":"images/img_2.jpg"
          },
          {
            "id":uuidv4(),
            "category":"Business",
            "category2":"Travel",
            "date":"July 2, 2020",
            "title":"Your most unhappy customers are your greatest source of learning.",
            "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "author":"Sergy Campbell",
            "designation":"CEO and Founder",
            "image":"images/person_1.jpg",
            "blog_image":"images/img_2.jpg"
          },
          {
            "id":uuidv4(),
            "category":"Business",
            "category2":"Travel",
            "date":"July 2, 2020",
            "title":"Your most unhappy customers are your greatest source of learning.",
            "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "author":"Sergy Campbell",
            "designation":"CEO and Founder",
            "image":"images/person_1.jpg",
            "blog_image":"images/img_2.jpg"
          },
          {
            "id":uuidv4(),
            "category":"Business",
            "category2":"Travel",
            "date":"July 2, 2020",
            "title":"Your most unhappy customers are your greatest source of learning.",
            "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
            "author":"Sergy Campbell",
            "designation":"CEO and Founder",
            "image":"images/person_1.jpg",
            "blog_image":"images/img_2.jpg"
          },
          {
              "id":uuidv4(),
              "category":"Business",
              "category2":"Travel",
              "date":"July 2, 2020",
              "title":"Your most unhappy customers are your greatest source of learning.",
              "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "author":"Sergy Campbell",
              "designation":"CEO and Founder",
              "image":"images/person_1.jpg",
              "blog_image":"images/img_2.jpg"
            },
            {
              "id":uuidv4(),
              "category":"Business",
              "category2":"Travel",
              "date":"July 2, 2020",
              "title":"Your most unhappy customers are your greatest source of learning.",
              "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "author":"Sergy Campbell",
              "designation":"CEO and Founder",
              "image":"images/person_1.jpg",
              "blog_image":"images/img_2.jpg"
            },
            {
              "id":uuidv4(),
              "category":"Business",
              "category2":"Travel",
              "date":"July 2, 2020",
              "title":"Your most unhappy customers are your greatest source of learning.",
              "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "author":"Sergy Campbell",
              "designation":"CEO and Founder",
              "image":"images/person_1.jpg",
              "blog_image":"images/img_2.jpg"
            },
            {
              "id":uuidv4(),
              "category":"Business",
              "category2":"Travel",
              "date":"July 2, 2020",
              "title":"Your most unhappy customers are your greatest source of learning.",
              "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "author":"Sergy Campbell",
              "designation":"CEO and Founder",
              "image":"images/person_1.jpg",
              "blog_image":"images/img_2.jpg"
            },
            {
              "id":uuidv4(),
              "category":"Business",
              "category2":"Travel",
              "date":"July 2, 2020",
              "title":"Your most unhappy customers are your greatest source of learning.",
              "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "author":"Sergy Campbell",
              "designation":"CEO and Founder",
              "image":"images/person_1.jpg",
              "blog_image":"images/img_2.jpg"
            },
            {
              "id":uuidv4(),
              "category":"Business",
              "category2":"Travel",
              "date":"July 2, 2020",
              "title":"Your most unhappy customers are your greatest source of learning.",
              "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
              "author":"Sergy Campbell",
              "designation":"CEO and Founder",
              "image":"images/person_1.jpg",
              "blog_image":"images/img_2.jpg"
            },
            {
                "id":uuidv4(),
                "category":"Business",
                "category2":"Travel",
                "date":"July 2, 2020",
                "title":"Your most unhappy customers are your greatest source of learning.",
                "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "author":"Sergy Campbell",
                "designation":"CEO and Founder",
                "image":"images/person_1.jpg",
                "blog_image":"images/img_2.jpg"
              },
              {
                "id":uuidv4(),
                "category":"Business",
                "category2":"Travel",
                "date":"July 2, 2020",
                "title":"Your most unhappy customers are your greatest source of learning.",
                "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "author":"Sergy Campbell",
                "designation":"CEO and Founder",
                "image":"images/person_1.jpg",
                "blog_image":"images/img_2.jpg"
              },
              {
                "id":uuidv4(),
                "category":"Business",
                "category2":"Travel",
                "date":"July 2, 2020",
                "title":"Your most unhappy customers are your greatest source of learning.",
                "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "author":"Sergy Campbell",
                "designation":"CEO and Founder",
                "image":"images/person_1.jpg",
                "blog_image":"images/img_2.jpg"
              },
              {
                "id":uuidv4(),
                "category":"Business",
                "category2":"Travel",
                "date":"July 2, 2020",
                "title":"Your most unhappy customers are your greatest source of learning.",
                "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "author":"Sergy Campbell",
                "designation":"CEO and Founder",
                "image":"images/person_1.jpg",
                "blog_image":"images/img_2.jpg"
              },
              {
                "id":uuidv4(),
                "category":"Business",
                "category2":"Travel",
                "date":"July 2, 2020",
                "title":"Your most unhappy customers are your greatest source of learning.",
                "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "author":"Sergy Campbell",
                "designation":"CEO and Founder",
                "image":"images/person_1.jpg",
                "blog_image":"images/img_2.jpg"
              } ,
              {
                "id":uuidv4(),
                "category":"Business",
                "category2":"Travel",
                "date":"July 2, 2020",
                "title":"Your most unhappy customers are your greatest source of learning.",
                "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                "author":"Sergy Campbell",
                "designation":"CEO and Founder",
                "image":"images/person_1.jpg",
                "blog_image":"images/img_2.jpg"
              },
              {
                  "id":uuidv4(),
                  "category":"Business",
                  "category2":"Travel",
                  "date":"July 2, 2020",
                  "title":"Your most unhappy customers are your greatest source of learning.",
                  "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "author":"Sergy Campbell",
                  "designation":"CEO and Founder",
                  "image":"images/person_1.jpg",
                  "blog_image":"images/img_2.jpg"
                },
                {
                  "id":uuidv4(),
                  "category":"Business",
                  "category2":"Travel",
                  "date":"July 2, 2020",
                  "title":"Your most unhappy customers are your greatest source of learning.",
                  "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "author":"Sergy Campbell",
                  "designation":"CEO and Founder",
                  "image":"images/person_1.jpg",
                  "blog_image":"images/img_2.jpg"
                },
                {
                  "id":uuidv4(),
                  "category":"Business",
                  "category2":"Travel",
                  "date":"July 2, 2020",
                  "title":"Your most unhappy customers are your greatest source of learning.",
                  "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "author":"Sergy Campbell",
                  "designation":"CEO and Founder",
                  "image":"images/person_1.jpg",
                  "blog_image":"images/img_2.jpg"
                },
                {
                  "id":uuidv4(),
                  "category":"Business",
                  "category2":"Travel",
                  "date":"July 2, 2020",
                  "title":"Your most unhappy customers are your greatest source of learning.",
                  "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "author":"Sergy Campbell",
                  "designation":"CEO and Founder",
                  "image":"images/person_1.jpg",
                  "blog_image":"images/img_2.jpg"
                },
                {
                  "id":uuidv4(),
                  "category":"Business",
                  "category2":"Travel",
                  "date":"July 2, 2020",
                  "title":"Your most unhappy customers are your greatest source of learning.",
                  "mini_description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "description":"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
                  "author":"Sergy Campbell",
                  "designation":"CEO and Founder",
                  "image":"images/person_1.jpg",
                  "blog_image":"images/img_2.jpg"
                } 
]



export default blogs;